# Generated by Django 4.1.5 on 2023-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('temperature', models.FloatField()),
                ('date_of_measurement', models.DateTimeField()),
            ],
        ),
    ]
